version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    networks:
      - kafka-cluster

  kafka0:
    image: wurstmeister/kafka
    container_name: kafka0
    restart: always
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka0:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
    networks:
      - kafka-cluster

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9093
    networks:
      - kafka-cluster

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    restart: always
    ports:
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9094
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9094
    networks:
      - kafka-cluster

  kafka-map:
    image: dushixiang/kafka-map:latest
    container_name: kafka-map
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DEFAULT_USERNAME=admin
      - DEFAULT_PASSWORD=admin
    volumes:
      - /opt/kafka-map/data:/usr/local/kafka-map/data
    networks:
      - kafka-cluster
networks:
  kafka-cluster:
    driver: bridge
